@server = http://localhost:8080

@tokenuri = https://apjextabapsubdomain.authentication.eu10.hana.ondemand.com/oauth/token
@clientid = sb-caplabelprinting1-APJEXTABAPORG-dev!t149617
@clientsecret = xWUtNIBJCEEo773qQVTzMklmudw=
@serviceurl = https://apjextabaporg-dev-caplabelprinting1-srv.cfapps.eu10.hana.ondemand.com

###

# @name getToken
POST {{tokenuri}} HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Authorization: Basic {{clientid}}:{{clientsecret}}

client_id={{clientid}}
&grant_type=client_credentials


### 
# @name OutbDeliveryItem_render
@authToken = {{getToken.response.body.access_token}}
GET {{serviceurl}}/odata/v4/DNService/OutbDeliveryItem(DeliveryDocument='80000002',DeliveryDocumentItem='000010')/DNService.render(template='labelprint3|labelprint3') HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}





### OutbDeliveryHeader
# @name OutbDeliveryHeader_GET
GET {{serviceurl}}/odata/v4/DNService/OutbDeliveryHeader
Content-Type: application/json
Authorization: Bearer {{authToken}}


### OutbDeliveryItem
# @name OutbDeliveryItem_GET

@authToken = {{getToken.response.body.access_token}}
GET {{serviceurl}}/odata/v4/DNService/OutbDeliveryItem
Content-Type: application/json
Authorization: Bearer {{authToken}}





###  getTemplate
# @name getTemplate
@authToken = {{getToken.response.body.access_token}}
GET {{serviceurl}}/odata/v4/DNService/getTemplates()
Content-Type: application/json
Authorization: Bearer {{authToken}}




###  getPrintQ
# @name getPrintQs   
@authToken = {{getToken.response.body.access_token}}
GET {{serviceurl}}/odata/v4/DNService/getPrintQs()
Content-Type: application/json
Authorization: Bearer {{authToken}}



###  getHeaderbyKey
# @name getHeaderbyKey   
@authToken = {{getToken.response.body.access_token}}
GET {{serviceurl}}/odata/v4/DNService/OutbDeliveryHeader(DeliveryDocument='80000002')/Items(DeliveryDocument='80000002',DeliveryDocumentItem='000010')
Content-Type: application/json
Authorization: Bearer {{authToken}}


###  getHeaderrednder
# @name getHeaderrednder
@authToken = {{getToken.response.body.access_token}}
GET {{serviceurl}}/odata/v4/DNService/OutbDeliveryHeader(DeliveryDocument='80000002')/Items(DeliveryDocument='80000002',DeliveryDocumentItem='000010')/DNService.render(template='labelprint3//labelprint3')
Content-Type: application/json
Authorization: Bearer {{authToken}}


###  getmetadata
# @name getmetadata
GET {{server}}/odata/v4/DNService/$metadata


###  render
# @name render
GET {{server}}/odata/v4/DNService/render()



###  itenrender 
# @name itenrender 

GET {{server}}/odata/v4/DNService/OutbDeliveryItem(DeliveryDocument='80000002',DeliveryDocumentItem='000010')/DNService.render(template='labelprint3//labelprint3')



###  itemmeatadata
# @name itemmeatadata

GET {{server}}/odata/v4/DNService/$metadata#OutbDeliveryItem



###  batch
# @name batch
@authToken = {{getToken.response.body.access_token}}
POST {{serviceurl}}/odata/v4/DNService/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_id-1725243043495-173
Authorization: Bearer {{authToken}}


--batch_id-1725243043495-173
Content-Type:application/http
Content-Transfer-Encoding:binary

GET OutbDeliveryHeader?$count=true&$select=ActualDeliveryRoute,ActualGoodsMovementDate,BillOfLading,BillingDocumentDate,DeliveryDate,DeliveryDocument,DocumentDate,HeaderGrossWeight,HeaderNetWeight,HeaderVolume,HeaderVolumeUnit,HeaderWeightUnit&$skip=0&$top=30 HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true


--batch_id-1725243043495-173--
Group ID: $auto.Workers



###  batchfunction
# @name batchfunction
@authToken = {{getToken.response.body.access_token}}
POST {{serviceurl}}/odata/v4/DNService/$batch HTTP/1.1
Content-Type: multipart/mixed; boundary=batch_id-1725244837925-761
Authorization: Bearer {{authToken}}

--batch_id-1725244837925-761
Content-Type:application/http
Content-Transfer-Encoding:binary

GET getTemplates() HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en-US
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true


--batch_id-1725244837925-761
Content-Type:application/http
Content-Transfer-Encoding:binary

GET getPrintQs() HTTP/1.1
Accept:application/json;odata.metadata=minimal;IEEE754Compatible=true
Accept-Language:en-US
Content-Type:application/json;charset=UTF-8;IEEE754Compatible=true


--batch_id-1725244837925-761--
Group ID: $auto




###  print
# @name print

@pdfCont = ./pdfCont
@authToken = {{getToken.response.body.access_token}}

GET {{serviceurl}}/odata/v4/DNService/print(pdf='hello',fileName='80000001000010pdf',printQ='plant2') HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{authToken}}



