openapi: 3.0.0
x-odata-version: '4.0'
info:
  title: Create Document
  description: 'It creates a document object of the speciﬁed type (given by the cmis:objectTypeId property) in the (optionally) speciﬁed location. '
  version: '1.0'
servers:
- url: https://{subdomain}.cfapps.{region}.hana.ondemand.com
  description: Testing Server
  variables:
    subdomain:
      default: ''
    region:
      default: ''
security:
- OAuth2: []
x-sap-stateInfo:
  state: Active
x-sap-shortText: Creates a document in the specified location inside repository.
tags:
- name: Create Document
paths:
  /browser/{repository_id}/root:
    post:
      tags:
      - Create Document
      parameters:
      - name: repository_id
        in: path
        description: The repository to be used is identified using repository id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cmisaction:
                  description: In order to perform this particluar operation in a Repository,cmisaction parameter in an HTTP POST request must be:createDocument
                  type: string
                  example: createDocument
                propertyId[0]:
                  type: string
                  example: cmis:name
                propertyValue[0]:
                  description: Holds the value of propertyid[0]
                  type: string
                  example: test.json
                propertyId[1]:
                  type: string
                  example: cmis:objectTypeId
                propertyValue[1]:
                  description: Holds the value of propertyid[1]
                  type: string
                  example: cmis:document
                filename:
                  description: Holds the name of the file
                  type: string
                _charset_:
                  description: This parameter has semantics identical to the charset parameter of the application/xml media type
                  type: string
                  example: UTF-8
                includeAllowableActions:
                  description: If true, then the Repository must return the available actions for each object in the result set. Defaults to false.
                  type: boolean
                  example: 'true'
                succinct:
                  description: Acts as a query parameter
                  type: boolean
                  example: 'true'
                media:
                  description: uploads a file
                  type: string
                  format: binary
      summary: Creates a document in the root folder inside repository
      description: It creates a document object of the speciﬁed type (given by the cmis:objectTypeId property) in the root folder.
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object'
        '401':
          description: Invalid access token
          content:
            application/json:
              schema:
                type: string
        4XX:
          description: Invalid flow
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidflow'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
  /browser/{repository_id}/root/{directory_path}:
    post:
      tags:
      - Create Document
      parameters:
      - name: repository_id
        in: path
        description: The repository to be used is identified using repository id
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: directory_path
        in: path
        description: The folder path to create the document object.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cmisaction:
                  description: In order to perform this particluar operation in a Repository,cmisaction parameter in an HTTP POST request must be:createDocument
                  type: string
                  example: createDocument
                propertyId[0]:
                  type: string
                  example: cmis:name
                propertyValue[0]:
                  description: Holds the value of propertyid[0]
                  type: string
                  example: test.json
                propertyId[1]:
                  type: string
                  example: cmis:objectTypeId
                propertyValue[1]:
                  description: Holds the value of propertyid[1]
                  type: string
                  example: cmis:document
                filename:
                  description: Holds the name of the file
                  type: string
                _charset_:
                  description: This parameter has semantics identical to the charset parameter of the application/xml media type
                  type: string
                  example: UTF-8
                includeAllowableActions:
                  description: If true, then the Repository must return the available actions for each object in the result set. Defaults to false.
                  type: boolean
                  example: 'true'
                succinct:
                  description: Acts as a query parameter
                  type: boolean
                  example: 'true'
                media:
                  description: uploads a file
                  type: string
                  format: binary
      summary: Creates a document in the speciﬁed location inside repository
      description: It creates a document object of the speciﬁed type (given by the cmis:objectTypeId property) in the speciﬁed location.
      responses:
        '201':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/object'
        '401':
          description: Invalid access token
          content:
            application/json:
              schema:
                type: string
        4XX:
          description: Invalid flow
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/invalidflow'
        '500':
          description: Server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error'
components:
  schemas:
    object:
      type: object
      properties:
        succinctProperties:
          type: object
          properties:
            cmis:objectId:
              type: string
              example: vts_mR0EfTpcri1_TDHqM39fasTVI5akhVHDDX7-7eo
            sap:parentIds:
              type: array
              items:
                type: string
                example: 54c16370006fac14ec10fb06
            cmis:name:
              type: string
              example: Test.docx
            cmis:lastModifiedBy:
              type: string
              example: sb-1e6079ca-5822-41e0-9789-93a2f066d534!b32286|sdm-di-SDM_DI_QUAL-qual!b6551
            cmis:objectTypeId:
              type: string
              example: cmis:document
            cmis:lastModificationDate:
              type: number
              example: 1623853693632
            cmis:createdBy:
              type: string
              example: sb-1e6079ca-5822-41e0-9789-93a2f066d534!b32286|sdm-di-SDM_DI_QUAL-qual!b6551
            cmis:baseTypeId:
              type: string
              example: cmis:document
            sap:owner:
              type: string
              example: sb-1e6079ca-5822-41e0-9789-93a2f066d534!b32286|sdm-di-SDM_DI_QUAL-qual!b6551
            cmis:creationDate:
              type: number
              example: 1623853693632
            cmis:changeToken:
              type: string
              example: 0
        exactACL:
          type: boolean
    error:
      type: object
      properties:
        message:
          type: string
          description: error
          example: internal server error
    invalidflow:
      type: object
      properties:
        message:
          type: string
          description: error
        status:
          type: string
  securitySchemes:
    OAuth2:
      type: oauth2
      x-stable: true
      description: 'To use this API, you need to obtain the OAuth client credentials (client ID and secret) from SAP Document Management. After that, pass these client credentials to the SAP API token endpoint to obtain an access token.<br/>Permissions: Admin for Document Management, integration option via the scope SDM_Admin'
      flows:
        clientCredentials:
          tokenUrl: https://{identityzone}.authentication.{region}.hana.ondemand.com/oauth/token
          scopes: {}
