

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Constrait Violation error
 */
// CHECKSTYLE:OFF
public class APIError 
// CHECKSTYLE:ON
{
  @JsonProperty("errorMessage")
  private String errorMessage;

  @JsonProperty("jsonFieldName")
  private String jsonFieldName;

  @JsonProperty("jsonInvalidValue")
  private String jsonInvalidValue;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the errorMessage of this {@link APIError} instance and return the same instance.
    *
    * @param errorMessage  The errorMessage of this {@link APIError}
    * @return The same instance of this {@link APIError} class
    */
   @Nonnull public APIError errorMessage(@Nonnull final String errorMessage) {
    this.errorMessage = errorMessage;
    return this;
  }

   /**
    * Get errorMessage
    * @return errorMessage  The errorMessage of this {@link APIError} instance.
    */
  @Nonnull public String getErrorMessage() {
    return errorMessage;
  }

  /**
   * Set the errorMessage of this {@link APIError} instance.
   *
   * @param errorMessage  The errorMessage of this {@link APIError}
   */
  public void setErrorMessage( @Nonnull final String errorMessage) {
    this.errorMessage = errorMessage;
  }

   /**
    * Set the jsonFieldName of this {@link APIError} instance and return the same instance.
    *
    * @param jsonFieldName  The jsonFieldName of this {@link APIError}
    * @return The same instance of this {@link APIError} class
    */
   @Nonnull public APIError jsonFieldName(@Nonnull final String jsonFieldName) {
    this.jsonFieldName = jsonFieldName;
    return this;
  }

   /**
    * Get jsonFieldName
    * @return jsonFieldName  The jsonFieldName of this {@link APIError} instance.
    */
  @Nonnull public String getJsonFieldName() {
    return jsonFieldName;
  }

  /**
   * Set the jsonFieldName of this {@link APIError} instance.
   *
   * @param jsonFieldName  The jsonFieldName of this {@link APIError}
   */
  public void setJsonFieldName( @Nonnull final String jsonFieldName) {
    this.jsonFieldName = jsonFieldName;
  }

   /**
    * Set the jsonInvalidValue of this {@link APIError} instance and return the same instance.
    *
    * @param jsonInvalidValue  The jsonInvalidValue of this {@link APIError}
    * @return The same instance of this {@link APIError} class
    */
   @Nonnull public APIError jsonInvalidValue(@Nonnull final String jsonInvalidValue) {
    this.jsonInvalidValue = jsonInvalidValue;
    return this;
  }

   /**
    * Get jsonInvalidValue
    * @return jsonInvalidValue  The jsonInvalidValue of this {@link APIError} instance.
    */
  @Nonnull public String getJsonInvalidValue() {
    return jsonInvalidValue;
  }

  /**
   * Set the jsonInvalidValue of this {@link APIError} instance.
   *
   * @param jsonInvalidValue  The jsonInvalidValue of this {@link APIError}
   */
  public void setJsonInvalidValue( @Nonnull final String jsonInvalidValue) {
    this.jsonInvalidValue = jsonInvalidValue;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link APIError}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link APIError} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("APIError has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link APIError} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final APIError apIError = (APIError) o;
    return Objects.equals(this.cloudSdkCustomFields, apIError.cloudSdkCustomFields) &&
        Objects.equals(this.errorMessage, apIError.errorMessage) &&
        Objects.equals(this.jsonFieldName, apIError.jsonFieldName) &&
        Objects.equals(this.jsonInvalidValue, apIError.jsonInvalidValue);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorMessage, jsonFieldName, jsonInvalidValue, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class APIError {\n");
    sb.append("    errorMessage: ").append(toIndentedString(errorMessage)).append("\n");
    sb.append("    jsonFieldName: ").append(toIndentedString(jsonFieldName)).append("\n");
    sb.append("    jsonInvalidValue: ").append(toIndentedString(jsonInvalidValue)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

