

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.caplabelprinting1.btpservice.ads.model.APIError;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * API Validation error response
 */
// CHECKSTYLE:OFF
public class APIValidationError 
// CHECKSTYLE:ON
{
  @JsonProperty("errorLevel")
  private String errorLevel;

  /**
   * Gets or Sets message
   */
  public enum MessageEnum {
    /**
    * The _100_CONTINUE option of this APIValidationError
    */
    _100_CONTINUE("100 CONTINUE"),
    
    /**
    * The _101_SWITCHING_PROTOCOLS option of this APIValidationError
    */
    _101_SWITCHING_PROTOCOLS("101 SWITCHING_PROTOCOLS"),
    
    /**
    * The _102_PROCESSING option of this APIValidationError
    */
    _102_PROCESSING("102 PROCESSING"),
    
    /**
    * The _103_EARLY_HINTS option of this APIValidationError
    */
    _103_EARLY_HINTS("103 EARLY_HINTS"),
    
    /**
    * The _103_CHECKPOINT option of this APIValidationError
    */
    _103_CHECKPOINT("103 CHECKPOINT"),
    
    /**
    * The _200_OK option of this APIValidationError
    */
    _200_OK("200 OK"),
    
    /**
    * The _201_CREATED option of this APIValidationError
    */
    _201_CREATED("201 CREATED"),
    
    /**
    * The _202_ACCEPTED option of this APIValidationError
    */
    _202_ACCEPTED("202 ACCEPTED"),
    
    /**
    * The _203_NON_AUTHORITATIVE_INFORMATION option of this APIValidationError
    */
    _203_NON_AUTHORITATIVE_INFORMATION("203 NON_AUTHORITATIVE_INFORMATION"),
    
    /**
    * The _204_NO_CONTENT option of this APIValidationError
    */
    _204_NO_CONTENT("204 NO_CONTENT"),
    
    /**
    * The _205_RESET_CONTENT option of this APIValidationError
    */
    _205_RESET_CONTENT("205 RESET_CONTENT"),
    
    /**
    * The _206_PARTIAL_CONTENT option of this APIValidationError
    */
    _206_PARTIAL_CONTENT("206 PARTIAL_CONTENT"),
    
    /**
    * The _207_MULTI_STATUS option of this APIValidationError
    */
    _207_MULTI_STATUS("207 MULTI_STATUS"),
    
    /**
    * The _208_ALREADY_REPORTED option of this APIValidationError
    */
    _208_ALREADY_REPORTED("208 ALREADY_REPORTED"),
    
    /**
    * The _226_IM_USED option of this APIValidationError
    */
    _226_IM_USED("226 IM_USED"),
    
    /**
    * The _300_MULTIPLE_CHOICES option of this APIValidationError
    */
    _300_MULTIPLE_CHOICES("300 MULTIPLE_CHOICES"),
    
    /**
    * The _301_MOVED_PERMANENTLY option of this APIValidationError
    */
    _301_MOVED_PERMANENTLY("301 MOVED_PERMANENTLY"),
    
    /**
    * The _302_FOUND option of this APIValidationError
    */
    _302_FOUND("302 FOUND"),
    
    /**
    * The _302_MOVED_TEMPORARILY option of this APIValidationError
    */
    _302_MOVED_TEMPORARILY("302 MOVED_TEMPORARILY"),
    
    /**
    * The _303_SEE_OTHER option of this APIValidationError
    */
    _303_SEE_OTHER("303 SEE_OTHER"),
    
    /**
    * The _304_NOT_MODIFIED option of this APIValidationError
    */
    _304_NOT_MODIFIED("304 NOT_MODIFIED"),
    
    /**
    * The _305_USE_PROXY option of this APIValidationError
    */
    _305_USE_PROXY("305 USE_PROXY"),
    
    /**
    * The _307_TEMPORARY_REDIRECT option of this APIValidationError
    */
    _307_TEMPORARY_REDIRECT("307 TEMPORARY_REDIRECT"),
    
    /**
    * The _308_PERMANENT_REDIRECT option of this APIValidationError
    */
    _308_PERMANENT_REDIRECT("308 PERMANENT_REDIRECT"),
    
    /**
    * The _400_BAD_REQUEST option of this APIValidationError
    */
    _400_BAD_REQUEST("400 BAD_REQUEST"),
    
    /**
    * The _401_UNAUTHORIZED option of this APIValidationError
    */
    _401_UNAUTHORIZED("401 UNAUTHORIZED"),
    
    /**
    * The _402_PAYMENT_REQUIRED option of this APIValidationError
    */
    _402_PAYMENT_REQUIRED("402 PAYMENT_REQUIRED"),
    
    /**
    * The _403_FORBIDDEN option of this APIValidationError
    */
    _403_FORBIDDEN("403 FORBIDDEN"),
    
    /**
    * The _404_NOT_FOUND option of this APIValidationError
    */
    _404_NOT_FOUND("404 NOT_FOUND"),
    
    /**
    * The _405_METHOD_NOT_ALLOWED option of this APIValidationError
    */
    _405_METHOD_NOT_ALLOWED("405 METHOD_NOT_ALLOWED"),
    
    /**
    * The _406_NOT_ACCEPTABLE option of this APIValidationError
    */
    _406_NOT_ACCEPTABLE("406 NOT_ACCEPTABLE"),
    
    /**
    * The _407_PROXY_AUTHENTICATION_REQUIRED option of this APIValidationError
    */
    _407_PROXY_AUTHENTICATION_REQUIRED("407 PROXY_AUTHENTICATION_REQUIRED"),
    
    /**
    * The _408_REQUEST_TIMEOUT option of this APIValidationError
    */
    _408_REQUEST_TIMEOUT("408 REQUEST_TIMEOUT"),
    
    /**
    * The _409_CONFLICT option of this APIValidationError
    */
    _409_CONFLICT("409 CONFLICT"),
    
    /**
    * The _410_GONE option of this APIValidationError
    */
    _410_GONE("410 GONE"),
    
    /**
    * The _411_LENGTH_REQUIRED option of this APIValidationError
    */
    _411_LENGTH_REQUIRED("411 LENGTH_REQUIRED"),
    
    /**
    * The _412_PRECONDITION_FAILED option of this APIValidationError
    */
    _412_PRECONDITION_FAILED("412 PRECONDITION_FAILED"),
    
    /**
    * The _413_PAYLOAD_TOO_LARGE option of this APIValidationError
    */
    _413_PAYLOAD_TOO_LARGE("413 PAYLOAD_TOO_LARGE"),
    
    /**
    * The _413_REQUEST_ENTITY_TOO_LARGE option of this APIValidationError
    */
    _413_REQUEST_ENTITY_TOO_LARGE("413 REQUEST_ENTITY_TOO_LARGE"),
    
    /**
    * The _414_URI_TOO_LONG option of this APIValidationError
    */
    _414_URI_TOO_LONG("414 URI_TOO_LONG"),
    
    /**
    * The _414_REQUEST_URI_TOO_LONG option of this APIValidationError
    */
    _414_REQUEST_URI_TOO_LONG("414 REQUEST_URI_TOO_LONG"),
    
    /**
    * The _415_UNSUPPORTED_MEDIA_TYPE option of this APIValidationError
    */
    _415_UNSUPPORTED_MEDIA_TYPE("415 UNSUPPORTED_MEDIA_TYPE"),
    
    /**
    * The _416_REQUESTED_RANGE_NOT_SATISFIABLE option of this APIValidationError
    */
    _416_REQUESTED_RANGE_NOT_SATISFIABLE("416 REQUESTED_RANGE_NOT_SATISFIABLE"),
    
    /**
    * The _417_EXPECTATION_FAILED option of this APIValidationError
    */
    _417_EXPECTATION_FAILED("417 EXPECTATION_FAILED"),
    
    /**
    * The _418_I_AM_A_TEAPOT option of this APIValidationError
    */
    _418_I_AM_A_TEAPOT("418 I_AM_A_TEAPOT"),
    
    /**
    * The _419_INSUFFICIENT_SPACE_ON_RESOURCE option of this APIValidationError
    */
    _419_INSUFFICIENT_SPACE_ON_RESOURCE("419 INSUFFICIENT_SPACE_ON_RESOURCE"),
    
    /**
    * The _420_METHOD_FAILURE option of this APIValidationError
    */
    _420_METHOD_FAILURE("420 METHOD_FAILURE"),
    
    /**
    * The _421_DESTINATION_LOCKED option of this APIValidationError
    */
    _421_DESTINATION_LOCKED("421 DESTINATION_LOCKED"),
    
    /**
    * The _422_UNPROCESSABLE_ENTITY option of this APIValidationError
    */
    _422_UNPROCESSABLE_ENTITY("422 UNPROCESSABLE_ENTITY"),
    
    /**
    * The _423_LOCKED option of this APIValidationError
    */
    _423_LOCKED("423 LOCKED"),
    
    /**
    * The _424_FAILED_DEPENDENCY option of this APIValidationError
    */
    _424_FAILED_DEPENDENCY("424 FAILED_DEPENDENCY"),
    
    /**
    * The _425_TOO_EARLY option of this APIValidationError
    */
    _425_TOO_EARLY("425 TOO_EARLY"),
    
    /**
    * The _426_UPGRADE_REQUIRED option of this APIValidationError
    */
    _426_UPGRADE_REQUIRED("426 UPGRADE_REQUIRED"),
    
    /**
    * The _428_PRECONDITION_REQUIRED option of this APIValidationError
    */
    _428_PRECONDITION_REQUIRED("428 PRECONDITION_REQUIRED"),
    
    /**
    * The _429_TOO_MANY_REQUESTS option of this APIValidationError
    */
    _429_TOO_MANY_REQUESTS("429 TOO_MANY_REQUESTS"),
    
    /**
    * The _431_REQUEST_HEADER_FIELDS_TOO_LARGE option of this APIValidationError
    */
    _431_REQUEST_HEADER_FIELDS_TOO_LARGE("431 REQUEST_HEADER_FIELDS_TOO_LARGE"),
    
    /**
    * The _451_UNAVAILABLE_FOR_LEGAL_REASONS option of this APIValidationError
    */
    _451_UNAVAILABLE_FOR_LEGAL_REASONS("451 UNAVAILABLE_FOR_LEGAL_REASONS"),
    
    /**
    * The _500_INTERNAL_SERVER_ERROR option of this APIValidationError
    */
    _500_INTERNAL_SERVER_ERROR("500 INTERNAL_SERVER_ERROR"),
    
    /**
    * The _501_NOT_IMPLEMENTED option of this APIValidationError
    */
    _501_NOT_IMPLEMENTED("501 NOT_IMPLEMENTED"),
    
    /**
    * The _502_BAD_GATEWAY option of this APIValidationError
    */
    _502_BAD_GATEWAY("502 BAD_GATEWAY"),
    
    /**
    * The _503_SERVICE_UNAVAILABLE option of this APIValidationError
    */
    _503_SERVICE_UNAVAILABLE("503 SERVICE_UNAVAILABLE"),
    
    /**
    * The _504_GATEWAY_TIMEOUT option of this APIValidationError
    */
    _504_GATEWAY_TIMEOUT("504 GATEWAY_TIMEOUT"),
    
    /**
    * The _505_HTTP_VERSION_NOT_SUPPORTED option of this APIValidationError
    */
    _505_HTTP_VERSION_NOT_SUPPORTED("505 HTTP_VERSION_NOT_SUPPORTED"),
    
    /**
    * The _506_VARIANT_ALSO_NEGOTIATES option of this APIValidationError
    */
    _506_VARIANT_ALSO_NEGOTIATES("506 VARIANT_ALSO_NEGOTIATES"),
    
    /**
    * The _507_INSUFFICIENT_STORAGE option of this APIValidationError
    */
    _507_INSUFFICIENT_STORAGE("507 INSUFFICIENT_STORAGE"),
    
    /**
    * The _508_LOOP_DETECTED option of this APIValidationError
    */
    _508_LOOP_DETECTED("508 LOOP_DETECTED"),
    
    /**
    * The _509_BANDWIDTH_LIMIT_EXCEEDED option of this APIValidationError
    */
    _509_BANDWIDTH_LIMIT_EXCEEDED("509 BANDWIDTH_LIMIT_EXCEEDED"),
    
    /**
    * The _510_NOT_EXTENDED option of this APIValidationError
    */
    _510_NOT_EXTENDED("510 NOT_EXTENDED"),
    
    /**
    * The _511_NETWORK_AUTHENTICATION_REQUIRED option of this APIValidationError
    */
    _511_NETWORK_AUTHENTICATION_REQUIRED("511 NETWORK_AUTHENTICATION_REQUIRED");

    private String value;

    MessageEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type APIValidationError
    */
    @JsonCreator
    @Nonnull public static MessageEnum fromValue(@Nonnull final String value) {
      for (MessageEnum b : MessageEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("message")
  private MessageEnum message;

  @JsonProperty("path")
  private String path;

  @JsonProperty("results")
  private String results;

  @JsonProperty("timestamp")
  private OffsetDateTime timestamp;

  @JsonProperty("trace")
  private List<APIError> trace = new ArrayList<>();

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the errorLevel of this {@link APIValidationError} instance and return the same instance.
    *
    * @param errorLevel  The errorLevel of this {@link APIValidationError}
    * @return The same instance of this {@link APIValidationError} class
    */
   @Nonnull public APIValidationError errorLevel(@Nonnull final String errorLevel) {
    this.errorLevel = errorLevel;
    return this;
  }

   /**
    * Get errorLevel
    * @return errorLevel  The errorLevel of this {@link APIValidationError} instance.
    */
  @Nonnull public String getErrorLevel() {
    return errorLevel;
  }

  /**
   * Set the errorLevel of this {@link APIValidationError} instance.
   *
   * @param errorLevel  The errorLevel of this {@link APIValidationError}
   */
  public void setErrorLevel( @Nonnull final String errorLevel) {
    this.errorLevel = errorLevel;
  }

   /**
    * Set the message of this {@link APIValidationError} instance and return the same instance.
    *
    * @param message  The message of this {@link APIValidationError}
    * @return The same instance of this {@link APIValidationError} class
    */
   @Nonnull public APIValidationError message(@Nonnull final MessageEnum message) {
    this.message = message;
    return this;
  }

   /**
    * Get message
    * @return message  The message of this {@link APIValidationError} instance.
    */
  @Nonnull public MessageEnum getMessage() {
    return message;
  }

  /**
   * Set the message of this {@link APIValidationError} instance.
   *
   * @param message  The message of this {@link APIValidationError}
   */
  public void setMessage( @Nonnull final MessageEnum message) {
    this.message = message;
  }

   /**
    * Set the path of this {@link APIValidationError} instance and return the same instance.
    *
    * @param path  The path of this {@link APIValidationError}
    * @return The same instance of this {@link APIValidationError} class
    */
   @Nonnull public APIValidationError path(@Nonnull final String path) {
    this.path = path;
    return this;
  }

   /**
    * Get path
    * @return path  The path of this {@link APIValidationError} instance.
    */
  @Nonnull public String getPath() {
    return path;
  }

  /**
   * Set the path of this {@link APIValidationError} instance.
   *
   * @param path  The path of this {@link APIValidationError}
   */
  public void setPath( @Nonnull final String path) {
    this.path = path;
  }

   /**
    * Set the results of this {@link APIValidationError} instance and return the same instance.
    *
    * @param results  The results of this {@link APIValidationError}
    * @return The same instance of this {@link APIValidationError} class
    */
   @Nonnull public APIValidationError results(@Nonnull final String results) {
    this.results = results;
    return this;
  }

   /**
    * Get results
    * @return results  The results of this {@link APIValidationError} instance.
    */
  @Nonnull public String getResults() {
    return results;
  }

  /**
   * Set the results of this {@link APIValidationError} instance.
   *
   * @param results  The results of this {@link APIValidationError}
   */
  public void setResults( @Nonnull final String results) {
    this.results = results;
  }

   /**
    * Set the timestamp of this {@link APIValidationError} instance and return the same instance.
    *
    * @param timestamp  The timestamp of this {@link APIValidationError}
    * @return The same instance of this {@link APIValidationError} class
    */
   @Nonnull public APIValidationError timestamp(@Nonnull final OffsetDateTime timestamp) {
    this.timestamp = timestamp;
    return this;
  }

   /**
    * Get timestamp
    * @return timestamp  The timestamp of this {@link APIValidationError} instance.
    */
  @Nonnull public OffsetDateTime getTimestamp() {
    return timestamp;
  }

  /**
   * Set the timestamp of this {@link APIValidationError} instance.
   *
   * @param timestamp  The timestamp of this {@link APIValidationError}
   */
  public void setTimestamp( @Nonnull final OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }

   /**
    * Set the trace of this {@link APIValidationError} instance and return the same instance.
    *
    * @param trace  The trace of this {@link APIValidationError}
    * @return The same instance of this {@link APIValidationError} class
    */
   @Nonnull public APIValidationError trace(@Nonnull final List<APIError> trace) {
    this.trace = trace;
    return this;
  }
  /**
   * Add one trace instance to this {@link APIValidationError}.
   * @param traceItem The trace that should be added
   * @return The same instance of type {@link APIValidationError}
   */
  @Nonnull public APIValidationError addTraceItem( @Nonnull final APIError traceItem) {
    if (this.trace == null) {
      this.trace = new ArrayList<>();
    }
    this.trace.add(traceItem);
    return this;
  }

   /**
    * Get trace
    * @return trace  The trace of this {@link APIValidationError} instance.
    */
  @Nonnull public List<APIError> getTrace() {
    return trace;
  }

  /**
   * Set the trace of this {@link APIValidationError} instance.
   *
   * @param trace  The trace of this {@link APIValidationError}
   */
  public void setTrace( @Nonnull final List<APIError> trace) {
    this.trace = trace;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link APIValidationError}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link APIValidationError} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("APIValidationError has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link APIValidationError} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final APIValidationError apIValidationError = (APIValidationError) o;
    return Objects.equals(this.cloudSdkCustomFields, apIValidationError.cloudSdkCustomFields) &&
        Objects.equals(this.errorLevel, apIValidationError.errorLevel) &&
        Objects.equals(this.message, apIValidationError.message) &&
        Objects.equals(this.path, apIValidationError.path) &&
        Objects.equals(this.results, apIValidationError.results) &&
        Objects.equals(this.timestamp, apIValidationError.timestamp) &&
        Objects.equals(this.trace, apIValidationError.trace);
  }

  @Override
  public int hashCode() {
    return Objects.hash(errorLevel, message, path, results, timestamp, trace, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class APIValidationError {\n");
    sb.append("    errorLevel: ").append(toIndentedString(errorLevel)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    results: ").append(toIndentedString(results)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    trace: ").append(toIndentedString(trace)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

