

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * List of Attachments
 */
// CHECKSTYLE:OFF
public class AttachmentFile 
// CHECKSTYLE:ON
{
  @JsonProperty("creationDate")
  private String creationDate;

  @JsonProperty("description")
  private String description;

  @JsonProperty("fileContent")
  private String fileContent;

  @JsonProperty("fileName")
  private String fileName;

  @JsonProperty("id")
  private String id;

  @JsonProperty("mimeType")
  private String mimeType;

  @JsonProperty("modificationDate")
  private String modificationDate;

  @JsonProperty("size")
  private String size;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the creationDate of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param creationDate  Creationdate of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile creationDate(@Nonnull final String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
    * Creationdate of the file
    * @return creationDate  The creationDate of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getCreationDate() {
    return creationDate;
  }

  /**
   * Set the creationDate of this {@link AttachmentFile} instance.
   *
   * @param creationDate  Creationdate of the file
   */
  public void setCreationDate( @Nonnull final String creationDate) {
    this.creationDate = creationDate;
  }

   /**
    * Set the description of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param description  Description of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
    * Description of the file
    * @return description  The description of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link AttachmentFile} instance.
   *
   * @param description  Description of the file
   */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
    * Set the fileContent of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param fileContent  File encoded as Base64 string
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile fileContent(@Nonnull final String fileContent) {
    this.fileContent = fileContent;
    return this;
  }

   /**
    * File encoded as Base64 string
    * @return fileContent  The fileContent of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getFileContent() {
    return fileContent;
  }

  /**
   * Set the fileContent of this {@link AttachmentFile} instance.
   *
   * @param fileContent  File encoded as Base64 string
   */
  public void setFileContent( @Nonnull final String fileContent) {
    this.fileContent = fileContent;
  }

   /**
    * Set the fileName of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param fileName  Name of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile fileName(@Nonnull final String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
    * Name of the file
    * @return fileName  The fileName of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getFileName() {
    return fileName;
  }

  /**
   * Set the fileName of this {@link AttachmentFile} instance.
   *
   * @param fileName  Name of the file
   */
  public void setFileName( @Nonnull final String fileName) {
    this.fileName = fileName;
  }

   /**
    * Set the id of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param id  Id of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile id(@Nonnull final String id) {
    this.id = id;
    return this;
  }

   /**
    * Id of the file
    * @return id  The id of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getId() {
    return id;
  }

  /**
   * Set the id of this {@link AttachmentFile} instance.
   *
   * @param id  Id of the file
   */
  public void setId( @Nonnull final String id) {
    this.id = id;
  }

   /**
    * Set the mimeType of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param mimeType  Mimetype of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile mimeType(@Nonnull final String mimeType) {
    this.mimeType = mimeType;
    return this;
  }

   /**
    * Mimetype of the file
    * @return mimeType  The mimeType of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getMimeType() {
    return mimeType;
  }

  /**
   * Set the mimeType of this {@link AttachmentFile} instance.
   *
   * @param mimeType  Mimetype of the file
   */
  public void setMimeType( @Nonnull final String mimeType) {
    this.mimeType = mimeType;
  }

   /**
    * Set the modificationDate of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param modificationDate  Modificationdate of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile modificationDate(@Nonnull final String modificationDate) {
    this.modificationDate = modificationDate;
    return this;
  }

   /**
    * Modificationdate of the file
    * @return modificationDate  The modificationDate of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getModificationDate() {
    return modificationDate;
  }

  /**
   * Set the modificationDate of this {@link AttachmentFile} instance.
   *
   * @param modificationDate  Modificationdate of the file
   */
  public void setModificationDate( @Nonnull final String modificationDate) {
    this.modificationDate = modificationDate;
  }

   /**
    * Set the size of this {@link AttachmentFile} instance and return the same instance.
    *
    * @param size  Size of the file
    * @return The same instance of this {@link AttachmentFile} class
    */
   @Nonnull public AttachmentFile size(@Nonnull final String size) {
    this.size = size;
    return this;
  }

   /**
    * Size of the file
    * @return size  The size of this {@link AttachmentFile} instance.
    */
  @Nonnull public String getSize() {
    return size;
  }

  /**
   * Set the size of this {@link AttachmentFile} instance.
   *
   * @param size  Size of the file
   */
  public void setSize( @Nonnull final String size) {
    this.size = size;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link AttachmentFile}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link AttachmentFile} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("AttachmentFile has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link AttachmentFile} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final AttachmentFile attachmentFile = (AttachmentFile) o;
    return Objects.equals(this.cloudSdkCustomFields, attachmentFile.cloudSdkCustomFields) &&
        Objects.equals(this.creationDate, attachmentFile.creationDate) &&
        Objects.equals(this.description, attachmentFile.description) &&
        Objects.equals(this.fileContent, attachmentFile.fileContent) &&
        Objects.equals(this.fileName, attachmentFile.fileName) &&
        Objects.equals(this.id, attachmentFile.id) &&
        Objects.equals(this.mimeType, attachmentFile.mimeType) &&
        Objects.equals(this.modificationDate, attachmentFile.modificationDate) &&
        Objects.equals(this.size, attachmentFile.size);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, description, fileContent, fileName, id, mimeType, modificationDate, size, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentFile {\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    fileContent: ").append(toIndentedString(fileContent)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mimeType: ").append(toIndentedString(mimeType)).append("\n");
    sb.append("    modificationDate: ").append(toIndentedString(modificationDate)).append("\n");
    sb.append("    size: ").append(toIndentedString(size)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

