

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.caplabelprinting1.btpservice.ads.model.AttachmentFile;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * AttachmentsOutput
 */
// CHECKSTYLE:OFF
public class AttachmentsOutput 
// CHECKSTYLE:ON
{
  @JsonProperty("attachments")
  private List<AttachmentFile> attachments = new ArrayList<>();

  @JsonProperty("traceString")
  private String traceString;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the attachments of this {@link AttachmentsOutput} instance and return the same instance.
    *
    * @param attachments  List of Attachments
    * @return The same instance of this {@link AttachmentsOutput} class
    */
   @Nonnull public AttachmentsOutput attachments(@Nonnull final List<AttachmentFile> attachments) {
    this.attachments = attachments;
    return this;
  }
  /**
   * Add one attachments instance to this {@link AttachmentsOutput}.
   * @param attachmentsItem The attachments that should be added
   * @return The same instance of type {@link AttachmentsOutput}
   */
  @Nonnull public AttachmentsOutput addAttachmentsItem( @Nonnull final AttachmentFile attachmentsItem) {
    if (this.attachments == null) {
      this.attachments = new ArrayList<>();
    }
    this.attachments.add(attachmentsItem);
    return this;
  }

   /**
    * List of Attachments
    * @return attachments  The attachments of this {@link AttachmentsOutput} instance.
    */
  @Nonnull public List<AttachmentFile> getAttachments() {
    return attachments;
  }

  /**
   * Set the attachments of this {@link AttachmentsOutput} instance.
   *
   * @param attachments  List of Attachments
   */
  public void setAttachments( @Nonnull final List<AttachmentFile> attachments) {
    this.attachments = attachments;
  }

   /**
    * Set the traceString of this {@link AttachmentsOutput} instance and return the same instance.
    *
    * @param traceString  Added if TraceLevel &gt; 0.
    * @return The same instance of this {@link AttachmentsOutput} class
    */
   @Nonnull public AttachmentsOutput traceString(@Nonnull final String traceString) {
    this.traceString = traceString;
    return this;
  }

   /**
    * Added if TraceLevel &gt; 0.
    * @return traceString  The traceString of this {@link AttachmentsOutput} instance.
    */
  @Nonnull public String getTraceString() {
    return traceString;
  }

  /**
   * Set the traceString of this {@link AttachmentsOutput} instance.
   *
   * @param traceString  Added if TraceLevel &gt; 0.
   */
  public void setTraceString( @Nonnull final String traceString) {
    this.traceString = traceString;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link AttachmentsOutput}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link AttachmentsOutput} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("AttachmentsOutput has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link AttachmentsOutput} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final AttachmentsOutput attachmentsOutput = (AttachmentsOutput) o;
    return Objects.equals(this.cloudSdkCustomFields, attachmentsOutput.cloudSdkCustomFields) &&
        Objects.equals(this.attachments, attachmentsOutput.attachments) &&
        Objects.equals(this.traceString, attachmentsOutput.traceString);
  }

  @Override
  public int hashCode() {
    return Objects.hash(attachments, traceString, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class AttachmentsOutput {\n");
    sb.append("    attachments: ").append(toIndentedString(attachments)).append("\n");
    sb.append("    traceString: ").append(toIndentedString(traceString)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

