

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Certificate
 */
// CHECKSTYLE:OFF
public class Certificate 
// CHECKSTYLE:ON
{
  @JsonProperty("cert")
  private String cert;

  @JsonProperty("status")
  private String status;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the cert of this {@link Certificate} instance and return the same instance.
    *
    * @param cert  The cert of this {@link Certificate}
    * @return The same instance of this {@link Certificate} class
    */
   @Nonnull public Certificate cert(@Nonnull final String cert) {
    this.cert = cert;
    return this;
  }

   /**
    * Get cert
    * @return cert  The cert of this {@link Certificate} instance.
    */
  @Nonnull public String getCert() {
    return cert;
  }

  /**
   * Set the cert of this {@link Certificate} instance.
   *
   * @param cert  The cert of this {@link Certificate}
   */
  public void setCert( @Nonnull final String cert) {
    this.cert = cert;
  }

   /**
    * Set the status of this {@link Certificate} instance and return the same instance.
    *
    * @param status  The status of this {@link Certificate}
    * @return The same instance of this {@link Certificate} class
    */
   @Nonnull public Certificate status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
    * Get status
    * @return status  The status of this {@link Certificate} instance.
    */
  @Nonnull public String getStatus() {
    return status;
  }

  /**
   * Set the status of this {@link Certificate} instance.
   *
   * @param status  The status of this {@link Certificate}
   */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link Certificate}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link Certificate} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("Certificate has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link Certificate} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final Certificate certificate = (Certificate) o;
    return Objects.equals(this.cloudSdkCustomFields, certificate.cloudSdkCustomFields) &&
        Objects.equals(this.cert, certificate.cert) &&
        Objects.equals(this.status, certificate.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cert, status, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class Certificate {\n");
    sb.append("    cert: ").append(toIndentedString(cert)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

