

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * FileVersionInfo
 */
// CHECKSTYLE:OFF
public class FileVersionInfo 
// CHECKSTYLE:ON
{
  @JsonProperty("isLatestVersion")
  private Boolean isLatestVersion;

  @JsonProperty("lastModificationDate")
  private String lastModificationDate;

  @JsonProperty("versionNumber")
  private String versionNumber;

  @JsonProperty("versionObjectId")
  private String versionObjectId;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the isLatestVersion of this {@link FileVersionInfo} instance and return the same instance.
    *
    * @param isLatestVersion  The isLatestVersion of this {@link FileVersionInfo}
    * @return The same instance of this {@link FileVersionInfo} class
    */
   @Nonnull public FileVersionInfo isLatestVersion(@Nonnull final Boolean isLatestVersion) {
    this.isLatestVersion = isLatestVersion;
    return this;
  }

   /**
    * Get isLatestVersion
    * @return isLatestVersion  The isLatestVersion of this {@link FileVersionInfo} instance.
    */
  @Nonnull public Boolean isIsLatestVersion() {
    return isLatestVersion;
  }

  /**
   * Set the isLatestVersion of this {@link FileVersionInfo} instance.
   *
   * @param isLatestVersion  The isLatestVersion of this {@link FileVersionInfo}
   */
  public void setIsLatestVersion( @Nonnull final Boolean isLatestVersion) {
    this.isLatestVersion = isLatestVersion;
  }

   /**
    * Set the lastModificationDate of this {@link FileVersionInfo} instance and return the same instance.
    *
    * @param lastModificationDate  The lastModificationDate of this {@link FileVersionInfo}
    * @return The same instance of this {@link FileVersionInfo} class
    */
   @Nonnull public FileVersionInfo lastModificationDate(@Nonnull final String lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
    return this;
  }

   /**
    * Get lastModificationDate
    * @return lastModificationDate  The lastModificationDate of this {@link FileVersionInfo} instance.
    */
  @Nonnull public String getLastModificationDate() {
    return lastModificationDate;
  }

  /**
   * Set the lastModificationDate of this {@link FileVersionInfo} instance.
   *
   * @param lastModificationDate  The lastModificationDate of this {@link FileVersionInfo}
   */
  public void setLastModificationDate( @Nonnull final String lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
  }

   /**
    * Set the versionNumber of this {@link FileVersionInfo} instance and return the same instance.
    *
    * @param versionNumber  The versionNumber of this {@link FileVersionInfo}
    * @return The same instance of this {@link FileVersionInfo} class
    */
   @Nonnull public FileVersionInfo versionNumber(@Nonnull final String versionNumber) {
    this.versionNumber = versionNumber;
    return this;
  }

   /**
    * Get versionNumber
    * @return versionNumber  The versionNumber of this {@link FileVersionInfo} instance.
    */
  @Nonnull public String getVersionNumber() {
    return versionNumber;
  }

  /**
   * Set the versionNumber of this {@link FileVersionInfo} instance.
   *
   * @param versionNumber  The versionNumber of this {@link FileVersionInfo}
   */
  public void setVersionNumber( @Nonnull final String versionNumber) {
    this.versionNumber = versionNumber;
  }

   /**
    * Set the versionObjectId of this {@link FileVersionInfo} instance and return the same instance.
    *
    * @param versionObjectId  The versionObjectId of this {@link FileVersionInfo}
    * @return The same instance of this {@link FileVersionInfo} class
    */
   @Nonnull public FileVersionInfo versionObjectId(@Nonnull final String versionObjectId) {
    this.versionObjectId = versionObjectId;
    return this;
  }

   /**
    * Get versionObjectId
    * @return versionObjectId  The versionObjectId of this {@link FileVersionInfo} instance.
    */
  @Nonnull public String getVersionObjectId() {
    return versionObjectId;
  }

  /**
   * Set the versionObjectId of this {@link FileVersionInfo} instance.
   *
   * @param versionObjectId  The versionObjectId of this {@link FileVersionInfo}
   */
  public void setVersionObjectId( @Nonnull final String versionObjectId) {
    this.versionObjectId = versionObjectId;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link FileVersionInfo}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link FileVersionInfo} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("FileVersionInfo has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link FileVersionInfo} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final FileVersionInfo fileVersionInfo = (FileVersionInfo) o;
    return Objects.equals(this.cloudSdkCustomFields, fileVersionInfo.cloudSdkCustomFields) &&
        Objects.equals(this.isLatestVersion, fileVersionInfo.isLatestVersion) &&
        Objects.equals(this.lastModificationDate, fileVersionInfo.lastModificationDate) &&
        Objects.equals(this.versionNumber, fileVersionInfo.versionNumber) &&
        Objects.equals(this.versionObjectId, fileVersionInfo.versionObjectId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(isLatestVersion, lastModificationDate, versionNumber, versionObjectId, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class FileVersionInfo {\n");
    sb.append("    isLatestVersion: ").append(toIndentedString(isLatestVersion)).append("\n");
    sb.append("    lastModificationDate: ").append(toIndentedString(lastModificationDate)).append("\n");
    sb.append("    versionNumber: ").append(toIndentedString(versionNumber)).append("\n");
    sb.append("    versionObjectId: ").append(toIndentedString(versionObjectId)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

