

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * FormMetadata
 */
// CHECKSTYLE:OFF
public class FormMetadata 
// CHECKSTYLE:ON
{
  @JsonProperty("creationDate")
  private String creationDate;

  @JsonProperty("lastModificationDate")
  private String lastModificationDate;

  @JsonProperty("managedBy")
  private String managedBy;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the creationDate of this {@link FormMetadata} instance and return the same instance.
    *
    * @param creationDate  The creationDate of this {@link FormMetadata}
    * @return The same instance of this {@link FormMetadata} class
    */
   @Nonnull public FormMetadata creationDate(@Nonnull final String creationDate) {
    this.creationDate = creationDate;
    return this;
  }

   /**
    * Get creationDate
    * @return creationDate  The creationDate of this {@link FormMetadata} instance.
    */
  @Nonnull public String getCreationDate() {
    return creationDate;
  }

  /**
   * Set the creationDate of this {@link FormMetadata} instance.
   *
   * @param creationDate  The creationDate of this {@link FormMetadata}
   */
  public void setCreationDate( @Nonnull final String creationDate) {
    this.creationDate = creationDate;
  }

   /**
    * Set the lastModificationDate of this {@link FormMetadata} instance and return the same instance.
    *
    * @param lastModificationDate  The lastModificationDate of this {@link FormMetadata}
    * @return The same instance of this {@link FormMetadata} class
    */
   @Nonnull public FormMetadata lastModificationDate(@Nonnull final String lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
    return this;
  }

   /**
    * Get lastModificationDate
    * @return lastModificationDate  The lastModificationDate of this {@link FormMetadata} instance.
    */
  @Nonnull public String getLastModificationDate() {
    return lastModificationDate;
  }

  /**
   * Set the lastModificationDate of this {@link FormMetadata} instance.
   *
   * @param lastModificationDate  The lastModificationDate of this {@link FormMetadata}
   */
  public void setLastModificationDate( @Nonnull final String lastModificationDate) {
    this.lastModificationDate = lastModificationDate;
  }

   /**
    * Set the managedBy of this {@link FormMetadata} instance and return the same instance.
    *
    * @param managedBy  The managedBy of this {@link FormMetadata}
    * @return The same instance of this {@link FormMetadata} class
    */
   @Nonnull public FormMetadata managedBy(@Nonnull final String managedBy) {
    this.managedBy = managedBy;
    return this;
  }

   /**
    * Get managedBy
    * @return managedBy  The managedBy of this {@link FormMetadata} instance.
    */
  @Nonnull public String getManagedBy() {
    return managedBy;
  }

  /**
   * Set the managedBy of this {@link FormMetadata} instance.
   *
   * @param managedBy  The managedBy of this {@link FormMetadata}
   */
  public void setManagedBy( @Nonnull final String managedBy) {
    this.managedBy = managedBy;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link FormMetadata}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link FormMetadata} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("FormMetadata has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link FormMetadata} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final FormMetadata formMetadata = (FormMetadata) o;
    return Objects.equals(this.cloudSdkCustomFields, formMetadata.cloudSdkCustomFields) &&
        Objects.equals(this.creationDate, formMetadata.creationDate) &&
        Objects.equals(this.lastModificationDate, formMetadata.lastModificationDate) &&
        Objects.equals(this.managedBy, formMetadata.managedBy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creationDate, lastModificationDate, managedBy, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class FormMetadata {\n");
    sb.append("    creationDate: ").append(toIndentedString(creationDate)).append("\n");
    sb.append("    lastModificationDate: ").append(toIndentedString(lastModificationDate)).append("\n");
    sb.append("    managedBy: ").append(toIndentedString(managedBy)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

