

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * SetSignature JSON. PDF encoded in BASE64.
 */
// CHECKSTYLE:OFF
public class SignatureInput 
// CHECKSTYLE:ON
{
  @JsonProperty("contactInfo")
  private String contactInfo;

  @JsonProperty("credentialAlias")
  private String credentialAlias;

  @JsonProperty("locationInfo")
  private String locationInfo;

  @JsonProperty("pdf")
  private String pdf = "Base64 String";

  @JsonProperty("reasonInfo")
  private String reasonInfo;

  @JsonProperty("signatureFieldName")
  private String signatureFieldName;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the contactInfo of this {@link SignatureInput} instance and return the same instance.
    *
    * @param contactInfo  The contactInfo of this {@link SignatureInput}
    * @return The same instance of this {@link SignatureInput} class
    */
   @Nonnull public SignatureInput contactInfo(@Nonnull final String contactInfo) {
    this.contactInfo = contactInfo;
    return this;
  }

   /**
    * Get contactInfo
    * @return contactInfo  The contactInfo of this {@link SignatureInput} instance.
    */
  @Nonnull public String getContactInfo() {
    return contactInfo;
  }

  /**
   * Set the contactInfo of this {@link SignatureInput} instance.
   *
   * @param contactInfo  The contactInfo of this {@link SignatureInput}
   */
  public void setContactInfo( @Nonnull final String contactInfo) {
    this.contactInfo = contactInfo;
  }

   /**
    * Set the credentialAlias of this {@link SignatureInput} instance and return the same instance.
    *
    * @param credentialAlias  The credentialAlias of this {@link SignatureInput}
    * @return The same instance of this {@link SignatureInput} class
    */
   @Nonnull public SignatureInput credentialAlias(@Nonnull final String credentialAlias) {
    this.credentialAlias = credentialAlias;
    return this;
  }

   /**
    * Get credentialAlias
    * @return credentialAlias  The credentialAlias of this {@link SignatureInput} instance.
    */
  @Nonnull public String getCredentialAlias() {
    return credentialAlias;
  }

  /**
   * Set the credentialAlias of this {@link SignatureInput} instance.
   *
   * @param credentialAlias  The credentialAlias of this {@link SignatureInput}
   */
  public void setCredentialAlias( @Nonnull final String credentialAlias) {
    this.credentialAlias = credentialAlias;
  }

   /**
    * Set the locationInfo of this {@link SignatureInput} instance and return the same instance.
    *
    * @param locationInfo  The locationInfo of this {@link SignatureInput}
    * @return The same instance of this {@link SignatureInput} class
    */
   @Nonnull public SignatureInput locationInfo(@Nonnull final String locationInfo) {
    this.locationInfo = locationInfo;
    return this;
  }

   /**
    * Get locationInfo
    * @return locationInfo  The locationInfo of this {@link SignatureInput} instance.
    */
  @Nonnull public String getLocationInfo() {
    return locationInfo;
  }

  /**
   * Set the locationInfo of this {@link SignatureInput} instance.
   *
   * @param locationInfo  The locationInfo of this {@link SignatureInput}
   */
  public void setLocationInfo( @Nonnull final String locationInfo) {
    this.locationInfo = locationInfo;
  }

   /**
    * Set the pdf of this {@link SignatureInput} instance and return the same instance.
    *
    * @param pdf  File encoded as Base64 string
    * @return The same instance of this {@link SignatureInput} class
    */
   @Nonnull public SignatureInput pdf(@Nonnull final String pdf) {
    this.pdf = pdf;
    return this;
  }

   /**
    * File encoded as Base64 string
    * @return pdf  The pdf of this {@link SignatureInput} instance.
    */
  @Nonnull public String getPdf() {
    return pdf;
  }

  /**
   * Set the pdf of this {@link SignatureInput} instance.
   *
   * @param pdf  File encoded as Base64 string
   */
  public void setPdf( @Nonnull final String pdf) {
    this.pdf = pdf;
  }

   /**
    * Set the reasonInfo of this {@link SignatureInput} instance and return the same instance.
    *
    * @param reasonInfo  The reasonInfo of this {@link SignatureInput}
    * @return The same instance of this {@link SignatureInput} class
    */
   @Nonnull public SignatureInput reasonInfo(@Nonnull final String reasonInfo) {
    this.reasonInfo = reasonInfo;
    return this;
  }

   /**
    * Get reasonInfo
    * @return reasonInfo  The reasonInfo of this {@link SignatureInput} instance.
    */
  @Nonnull public String getReasonInfo() {
    return reasonInfo;
  }

  /**
   * Set the reasonInfo of this {@link SignatureInput} instance.
   *
   * @param reasonInfo  The reasonInfo of this {@link SignatureInput}
   */
  public void setReasonInfo( @Nonnull final String reasonInfo) {
    this.reasonInfo = reasonInfo;
  }

   /**
    * Set the signatureFieldName of this {@link SignatureInput} instance and return the same instance.
    *
    * @param signatureFieldName  The signatureFieldName of this {@link SignatureInput}
    * @return The same instance of this {@link SignatureInput} class
    */
   @Nonnull public SignatureInput signatureFieldName(@Nonnull final String signatureFieldName) {
    this.signatureFieldName = signatureFieldName;
    return this;
  }

   /**
    * Get signatureFieldName
    * @return signatureFieldName  The signatureFieldName of this {@link SignatureInput} instance.
    */
  @Nonnull public String getSignatureFieldName() {
    return signatureFieldName;
  }

  /**
   * Set the signatureFieldName of this {@link SignatureInput} instance.
   *
   * @param signatureFieldName  The signatureFieldName of this {@link SignatureInput}
   */
  public void setSignatureFieldName( @Nonnull final String signatureFieldName) {
    this.signatureFieldName = signatureFieldName;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link SignatureInput}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link SignatureInput} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("SignatureInput has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link SignatureInput} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final SignatureInput signatureInput = (SignatureInput) o;
    return Objects.equals(this.cloudSdkCustomFields, signatureInput.cloudSdkCustomFields) &&
        Objects.equals(this.contactInfo, signatureInput.contactInfo) &&
        Objects.equals(this.credentialAlias, signatureInput.credentialAlias) &&
        Objects.equals(this.locationInfo, signatureInput.locationInfo) &&
        Objects.equals(this.pdf, signatureInput.pdf) &&
        Objects.equals(this.reasonInfo, signatureInput.reasonInfo) &&
        Objects.equals(this.signatureFieldName, signatureInput.signatureFieldName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contactInfo, credentialAlias, locationInfo, pdf, reasonInfo, signatureFieldName, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class SignatureInput {\n");
    sb.append("    contactInfo: ").append(toIndentedString(contactInfo)).append("\n");
    sb.append("    credentialAlias: ").append(toIndentedString(credentialAlias)).append("\n");
    sb.append("    locationInfo: ").append(toIndentedString(locationInfo)).append("\n");
    sb.append("    pdf: ").append(toIndentedString(pdf)).append("\n");
    sb.append("    reasonInfo: ").append(toIndentedString(reasonInfo)).append("\n");
    sb.append("    signatureFieldName: ").append(toIndentedString(signatureFieldName)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

