

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * Template JSON Input to update templates as part of a form entity. One form entity can have multiple templates.&lt;br /&gt;&lt;br /&gt;&lt;br /&gt;**XdpTemplate Options:** &#x60;Optional&#x60; Template file encoded as BASE64 string.&lt;br /&gt;&lt;br /&gt;**TemplateName Options:** &#x60;Optional&#x60; Limited to 30 characters. Only alphanumeric characters allowed and &#39;_&#39; character.&lt;br /&gt;&lt;br /&gt;**Description Options:** &#x60;Optional&#x60; Limited to 280 characters.&lt;br /&gt;&lt;br /&gt;**Note Options:** &#x60;Optional&#x60; Limited to 280 characters.&lt;br /&gt;&lt;br /&gt;**Locale Options:** &#x60;Optional&#x60; Combination of ISO-639 language code and ISO-3166 country code (language_country).&lt;br /&gt;&lt;br /&gt;**MasterLanguage Options:** &#x60;Optional&#x60; Limited to 280 characters.&lt;br /&gt;&lt;br /&gt;**BusinessArea Options:** &#x60;Optional&#x60; Limited to 280 characters.&lt;br /&gt;&lt;br /&gt;**BusinessDepartment Options:**; &#x60;Optional&#x60; Limited to 280 characters.
 */
// CHECKSTYLE:OFF
public class TemplateUpdateStoreInput 
// CHECKSTYLE:ON
{
  @JsonProperty("businessArea")
  private String businessArea;

  @JsonProperty("businessDepartment")
  private String businessDepartment;

  @JsonProperty("description")
  private String description;

  @JsonProperty("locale")
  private String locale;

  @JsonProperty("masterLanguage")
  private String masterLanguage;

  @JsonProperty("note")
  private String note;

  @JsonProperty("templateName")
  private String templateName;

  @JsonProperty("xdpTemplate")
  private String xdpTemplate = "Base64 String";

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the businessArea of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param businessArea  The businessArea of this {@link TemplateUpdateStoreInput}
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput businessArea(@Nonnull final String businessArea) {
    this.businessArea = businessArea;
    return this;
  }

   /**
    * Get businessArea
    * @return businessArea  The businessArea of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getBusinessArea() {
    return businessArea;
  }

  /**
   * Set the businessArea of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param businessArea  The businessArea of this {@link TemplateUpdateStoreInput}
   */
  public void setBusinessArea( @Nonnull final String businessArea) {
    this.businessArea = businessArea;
  }

   /**
    * Set the businessDepartment of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param businessDepartment  The businessDepartment of this {@link TemplateUpdateStoreInput}
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput businessDepartment(@Nonnull final String businessDepartment) {
    this.businessDepartment = businessDepartment;
    return this;
  }

   /**
    * Get businessDepartment
    * @return businessDepartment  The businessDepartment of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getBusinessDepartment() {
    return businessDepartment;
  }

  /**
   * Set the businessDepartment of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param businessDepartment  The businessDepartment of this {@link TemplateUpdateStoreInput}
   */
  public void setBusinessDepartment( @Nonnull final String businessDepartment) {
    this.businessDepartment = businessDepartment;
  }

   /**
    * Set the description of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param description  The description of this {@link TemplateUpdateStoreInput}
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
    * Get description
    * @return description  The description of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param description  The description of this {@link TemplateUpdateStoreInput}
   */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
    * Set the locale of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param locale  Locale must be &#39;language_country&#39; according to ISO 639
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput locale(@Nonnull final String locale) {
    this.locale = locale;
    return this;
  }

   /**
    * Locale must be &#39;language_country&#39; according to ISO 639
    * @return locale  The locale of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getLocale() {
    return locale;
  }

  /**
   * Set the locale of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param locale  Locale must be &#39;language_country&#39; according to ISO 639
   */
  public void setLocale( @Nonnull final String locale) {
    this.locale = locale;
  }

   /**
    * Set the masterLanguage of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param masterLanguage  The masterLanguage of this {@link TemplateUpdateStoreInput}
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput masterLanguage(@Nonnull final String masterLanguage) {
    this.masterLanguage = masterLanguage;
    return this;
  }

   /**
    * Get masterLanguage
    * @return masterLanguage  The masterLanguage of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getMasterLanguage() {
    return masterLanguage;
  }

  /**
   * Set the masterLanguage of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param masterLanguage  The masterLanguage of this {@link TemplateUpdateStoreInput}
   */
  public void setMasterLanguage( @Nonnull final String masterLanguage) {
    this.masterLanguage = masterLanguage;
  }

   /**
    * Set the note of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param note  The note of this {@link TemplateUpdateStoreInput}
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput note(@Nonnull final String note) {
    this.note = note;
    return this;
  }

   /**
    * Get note
    * @return note  The note of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getNote() {
    return note;
  }

  /**
   * Set the note of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param note  The note of this {@link TemplateUpdateStoreInput}
   */
  public void setNote( @Nonnull final String note) {
    this.note = note;
  }

   /**
    * Set the templateName of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param templateName  Form naming restricted to unicode letters or digits.
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput templateName(@Nonnull final String templateName) {
    this.templateName = templateName;
    return this;
  }

   /**
    * Form naming restricted to unicode letters or digits.
    * @return templateName  The templateName of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getTemplateName() {
    return templateName;
  }

  /**
   * Set the templateName of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param templateName  Form naming restricted to unicode letters or digits.
   */
  public void setTemplateName( @Nonnull final String templateName) {
    this.templateName = templateName;
  }

   /**
    * Set the xdpTemplate of this {@link TemplateUpdateStoreInput} instance and return the same instance.
    *
    * @param xdpTemplate  Template file encoded as Base64 string
    * @return The same instance of this {@link TemplateUpdateStoreInput} class
    */
   @Nonnull public TemplateUpdateStoreInput xdpTemplate(@Nonnull final String xdpTemplate) {
    this.xdpTemplate = xdpTemplate;
    return this;
  }

   /**
    * Template file encoded as Base64 string
    * @return xdpTemplate  The xdpTemplate of this {@link TemplateUpdateStoreInput} instance.
    */
  @Nonnull public String getXdpTemplate() {
    return xdpTemplate;
  }

  /**
   * Set the xdpTemplate of this {@link TemplateUpdateStoreInput} instance.
   *
   * @param xdpTemplate  Template file encoded as Base64 string
   */
  public void setXdpTemplate( @Nonnull final String xdpTemplate) {
    this.xdpTemplate = xdpTemplate;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TemplateUpdateStoreInput}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TemplateUpdateStoreInput} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TemplateUpdateStoreInput has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link TemplateUpdateStoreInput} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TemplateUpdateStoreInput templateUpdateStoreInput = (TemplateUpdateStoreInput) o;
    return Objects.equals(this.cloudSdkCustomFields, templateUpdateStoreInput.cloudSdkCustomFields) &&
        Objects.equals(this.businessArea, templateUpdateStoreInput.businessArea) &&
        Objects.equals(this.businessDepartment, templateUpdateStoreInput.businessDepartment) &&
        Objects.equals(this.description, templateUpdateStoreInput.description) &&
        Objects.equals(this.locale, templateUpdateStoreInput.locale) &&
        Objects.equals(this.masterLanguage, templateUpdateStoreInput.masterLanguage) &&
        Objects.equals(this.note, templateUpdateStoreInput.note) &&
        Objects.equals(this.templateName, templateUpdateStoreInput.templateName) &&
        Objects.equals(this.xdpTemplate, templateUpdateStoreInput.xdpTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessArea, businessDepartment, description, locale, masterLanguage, note, templateName, xdpTemplate, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TemplateUpdateStoreInput {\n");
    sb.append("    businessArea: ").append(toIndentedString(businessArea)).append("\n");
    sb.append("    businessDepartment: ").append(toIndentedString(businessDepartment)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    masterLanguage: ").append(toIndentedString(masterLanguage)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("    xdpTemplate: ").append(toIndentedString(xdpTemplate)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

