

/*
 * Forms Service by Adobe API (Cloud Foundry)
 * The SAP Forms service by Adobe is a cloud service based on the ADS (Adobe Document Services). The Forms service REST API provides a subset of the SAP Forms service capabilities. They are addressed by different URIs (Uniform Resource Identifiers) where each URI supports data and document exchange in a JSON format. The SAP Forms service REST API delivers a comprehensive description and is easy to test. The application calls the REST API via an SAP BTP subaccount that must be subscribed to the SAP Forms service.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.ads.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.caplabelprinting1.btpservice.ads.model.FileVersionInfo;
import customer.caplabelprinting1.btpservice.ads.model.TemplateMetadata;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * TemplateStoreOutput
 */
// CHECKSTYLE:OFF
public class TemplateStoreOutput 
// CHECKSTYLE:ON
{
  @JsonProperty("businessArea")
  private String businessArea;

  @JsonProperty("businessDepartment")
  private String businessDepartment;

  @JsonProperty("description")
  private String description;

  @JsonProperty("language")
  private String language;

  @JsonProperty("locale")
  private String locale;

  @JsonProperty("masterLanguage")
  private String masterLanguage;

  @JsonProperty("metaData")
  private TemplateMetadata metaData;

  @JsonProperty("note")
  private String note;

  @JsonProperty("templateName")
  private String templateName;

  @JsonProperty("versions")
  private List<FileVersionInfo> versions = new ArrayList<>();

  @JsonProperty("xdpTemplate")
  private String xdpTemplate = "Base64 String";

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the businessArea of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param businessArea  The businessArea of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput businessArea(@Nonnull final String businessArea) {
    this.businessArea = businessArea;
    return this;
  }

   /**
    * Get businessArea
    * @return businessArea  The businessArea of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getBusinessArea() {
    return businessArea;
  }

  /**
   * Set the businessArea of this {@link TemplateStoreOutput} instance.
   *
   * @param businessArea  The businessArea of this {@link TemplateStoreOutput}
   */
  public void setBusinessArea( @Nonnull final String businessArea) {
    this.businessArea = businessArea;
  }

   /**
    * Set the businessDepartment of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param businessDepartment  The businessDepartment of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput businessDepartment(@Nonnull final String businessDepartment) {
    this.businessDepartment = businessDepartment;
    return this;
  }

   /**
    * Get businessDepartment
    * @return businessDepartment  The businessDepartment of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getBusinessDepartment() {
    return businessDepartment;
  }

  /**
   * Set the businessDepartment of this {@link TemplateStoreOutput} instance.
   *
   * @param businessDepartment  The businessDepartment of this {@link TemplateStoreOutput}
   */
  public void setBusinessDepartment( @Nonnull final String businessDepartment) {
    this.businessDepartment = businessDepartment;
  }

   /**
    * Set the description of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param description  The description of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
    * Get description
    * @return description  The description of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getDescription() {
    return description;
  }

  /**
   * Set the description of this {@link TemplateStoreOutput} instance.
   *
   * @param description  The description of this {@link TemplateStoreOutput}
   */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
    * Set the language of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param language  The language of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput language(@Nonnull final String language) {
    this.language = language;
    return this;
  }

   /**
    * Get language
    * @return language  The language of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getLanguage() {
    return language;
  }

  /**
   * Set the language of this {@link TemplateStoreOutput} instance.
   *
   * @param language  The language of this {@link TemplateStoreOutput}
   */
  public void setLanguage( @Nonnull final String language) {
    this.language = language;
  }

   /**
    * Set the locale of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param locale  The locale of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput locale(@Nonnull final String locale) {
    this.locale = locale;
    return this;
  }

   /**
    * Get locale
    * @return locale  The locale of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getLocale() {
    return locale;
  }

  /**
   * Set the locale of this {@link TemplateStoreOutput} instance.
   *
   * @param locale  The locale of this {@link TemplateStoreOutput}
   */
  public void setLocale( @Nonnull final String locale) {
    this.locale = locale;
  }

   /**
    * Set the masterLanguage of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param masterLanguage  The masterLanguage of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput masterLanguage(@Nonnull final String masterLanguage) {
    this.masterLanguage = masterLanguage;
    return this;
  }

   /**
    * Get masterLanguage
    * @return masterLanguage  The masterLanguage of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getMasterLanguage() {
    return masterLanguage;
  }

  /**
   * Set the masterLanguage of this {@link TemplateStoreOutput} instance.
   *
   * @param masterLanguage  The masterLanguage of this {@link TemplateStoreOutput}
   */
  public void setMasterLanguage( @Nonnull final String masterLanguage) {
    this.masterLanguage = masterLanguage;
  }

   /**
    * Set the metaData of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param metaData  The metaData of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput metaData(@Nonnull final TemplateMetadata metaData) {
    this.metaData = metaData;
    return this;
  }

   /**
    * Get metaData
    * @return metaData  The metaData of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public TemplateMetadata getMetaData() {
    return metaData;
  }

  /**
   * Set the metaData of this {@link TemplateStoreOutput} instance.
   *
   * @param metaData  The metaData of this {@link TemplateStoreOutput}
   */
  public void setMetaData( @Nonnull final TemplateMetadata metaData) {
    this.metaData = metaData;
  }

   /**
    * Set the note of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param note  The note of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput note(@Nonnull final String note) {
    this.note = note;
    return this;
  }

   /**
    * Get note
    * @return note  The note of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getNote() {
    return note;
  }

  /**
   * Set the note of this {@link TemplateStoreOutput} instance.
   *
   * @param note  The note of this {@link TemplateStoreOutput}
   */
  public void setNote( @Nonnull final String note) {
    this.note = note;
  }

   /**
    * Set the templateName of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param templateName  The templateName of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput templateName(@Nonnull final String templateName) {
    this.templateName = templateName;
    return this;
  }

   /**
    * Get templateName
    * @return templateName  The templateName of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getTemplateName() {
    return templateName;
  }

  /**
   * Set the templateName of this {@link TemplateStoreOutput} instance.
   *
   * @param templateName  The templateName of this {@link TemplateStoreOutput}
   */
  public void setTemplateName( @Nonnull final String templateName) {
    this.templateName = templateName;
  }

   /**
    * Set the versions of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param versions  The versions of this {@link TemplateStoreOutput}
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput versions(@Nonnull final List<FileVersionInfo> versions) {
    this.versions = versions;
    return this;
  }
  /**
   * Add one versions instance to this {@link TemplateStoreOutput}.
   * @param versionsItem The versions that should be added
   * @return The same instance of type {@link TemplateStoreOutput}
   */
  @Nonnull public TemplateStoreOutput addVersionsItem( @Nonnull final FileVersionInfo versionsItem) {
    if (this.versions == null) {
      this.versions = new ArrayList<>();
    }
    this.versions.add(versionsItem);
    return this;
  }

   /**
    * Get versions
    * @return versions  The versions of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public List<FileVersionInfo> getVersions() {
    return versions;
  }

  /**
   * Set the versions of this {@link TemplateStoreOutput} instance.
   *
   * @param versions  The versions of this {@link TemplateStoreOutput}
   */
  public void setVersions( @Nonnull final List<FileVersionInfo> versions) {
    this.versions = versions;
  }

   /**
    * Set the xdpTemplate of this {@link TemplateStoreOutput} instance and return the same instance.
    *
    * @param xdpTemplate  Template file encoded as Base64 string
    * @return The same instance of this {@link TemplateStoreOutput} class
    */
   @Nonnull public TemplateStoreOutput xdpTemplate(@Nonnull final String xdpTemplate) {
    this.xdpTemplate = xdpTemplate;
    return this;
  }

   /**
    * Template file encoded as Base64 string
    * @return xdpTemplate  The xdpTemplate of this {@link TemplateStoreOutput} instance.
    */
  @Nonnull public String getXdpTemplate() {
    return xdpTemplate;
  }

  /**
   * Set the xdpTemplate of this {@link TemplateStoreOutput} instance.
   *
   * @param xdpTemplate  Template file encoded as Base64 string
   */
  public void setXdpTemplate( @Nonnull final String xdpTemplate) {
    this.xdpTemplate = xdpTemplate;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link TemplateStoreOutput}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link TemplateStoreOutput} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("TemplateStoreOutput has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link TemplateStoreOutput} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final TemplateStoreOutput templateStoreOutput = (TemplateStoreOutput) o;
    return Objects.equals(this.cloudSdkCustomFields, templateStoreOutput.cloudSdkCustomFields) &&
        Objects.equals(this.businessArea, templateStoreOutput.businessArea) &&
        Objects.equals(this.businessDepartment, templateStoreOutput.businessDepartment) &&
        Objects.equals(this.description, templateStoreOutput.description) &&
        Objects.equals(this.language, templateStoreOutput.language) &&
        Objects.equals(this.locale, templateStoreOutput.locale) &&
        Objects.equals(this.masterLanguage, templateStoreOutput.masterLanguage) &&
        Objects.equals(this.metaData, templateStoreOutput.metaData) &&
        Objects.equals(this.note, templateStoreOutput.note) &&
        Objects.equals(this.templateName, templateStoreOutput.templateName) &&
        Objects.equals(this.versions, templateStoreOutput.versions) &&
        Objects.equals(this.xdpTemplate, templateStoreOutput.xdpTemplate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessArea, businessDepartment, description, language, locale, masterLanguage, metaData, note, templateName, versions, xdpTemplate, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class TemplateStoreOutput {\n");
    sb.append("    businessArea: ").append(toIndentedString(businessArea)).append("\n");
    sb.append("    businessDepartment: ").append(toIndentedString(businessDepartment)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    language: ").append(toIndentedString(language)).append("\n");
    sb.append("    locale: ").append(toIndentedString(locale)).append("\n");
    sb.append("    masterLanguage: ").append(toIndentedString(masterLanguage)).append("\n");
    sb.append("    metaData: ").append(toIndentedString(metaData)).append("\n");
    sb.append("    note: ").append(toIndentedString(note)).append("\n");
    sb.append("    templateName: ").append(toIndentedString(templateName)).append("\n");
    sb.append("    versions: ").append(toIndentedString(versions)).append("\n");
    sb.append("    xdpTemplate: ").append(toIndentedString(xdpTemplate)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

