

/*
 * SAP Print Service
 * SAP Print service offers public APIs, including Query Print Queue, Upload Documents and Create Print Task that can help manage print queues, connect print clients and monitor print status.   This API is implemented based on REST API specification.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.print.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.LocalDate;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * PrintQueueDTO
 */
// CHECKSTYLE:OFF
public class PrintQueueDTO 
// CHECKSTYLE:ON
{
  @JsonProperty("qname")
  private String qname;

  @JsonProperty("qdescription")
  private String qdescription;

  @JsonProperty("qstatus")
  private String qstatus;

  @JsonProperty("qformat")
  private String qformat;

  @JsonProperty("cleanupPrd")
  private Integer cleanupPrd;

  @JsonProperty("techUserName")
  private String techUserName;

  @JsonProperty("creator")
  private String creator;

  @JsonProperty("createdOn")
  private LocalDate createdOn;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the qname of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param qname  The qname of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO qname(@Nonnull final String qname) {
    this.qname = qname;
    return this;
  }

   /**
    * Get qname
    * @return qname  The qname of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public String getQname() {
    return qname;
  }

  /**
   * Set the qname of this {@link PrintQueueDTO} instance.
   *
   * @param qname  The qname of this {@link PrintQueueDTO}
   */
  public void setQname( @Nonnull final String qname) {
    this.qname = qname;
  }

   /**
    * Set the qdescription of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param qdescription  The qdescription of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO qdescription(@Nonnull final String qdescription) {
    this.qdescription = qdescription;
    return this;
  }

   /**
    * Get qdescription
    * @return qdescription  The qdescription of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public String getQdescription() {
    return qdescription;
  }

  /**
   * Set the qdescription of this {@link PrintQueueDTO} instance.
   *
   * @param qdescription  The qdescription of this {@link PrintQueueDTO}
   */
  public void setQdescription( @Nonnull final String qdescription) {
    this.qdescription = qdescription;
  }

   /**
    * Set the qstatus of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param qstatus  The qstatus of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO qstatus(@Nonnull final String qstatus) {
    this.qstatus = qstatus;
    return this;
  }

   /**
    * Get qstatus
    * @return qstatus  The qstatus of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public String getQstatus() {
    return qstatus;
  }

  /**
   * Set the qstatus of this {@link PrintQueueDTO} instance.
   *
   * @param qstatus  The qstatus of this {@link PrintQueueDTO}
   */
  public void setQstatus( @Nonnull final String qstatus) {
    this.qstatus = qstatus;
  }

   /**
    * Set the qformat of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param qformat  The qformat of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO qformat(@Nonnull final String qformat) {
    this.qformat = qformat;
    return this;
  }

   /**
    * Get qformat
    * @return qformat  The qformat of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public String getQformat() {
    return qformat;
  }

  /**
   * Set the qformat of this {@link PrintQueueDTO} instance.
   *
   * @param qformat  The qformat of this {@link PrintQueueDTO}
   */
  public void setQformat( @Nonnull final String qformat) {
    this.qformat = qformat;
  }

   /**
    * Set the cleanupPrd of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param cleanupPrd  The cleanupPrd of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO cleanupPrd(@Nonnull final Integer cleanupPrd) {
    this.cleanupPrd = cleanupPrd;
    return this;
  }

   /**
    * Get cleanupPrd
    * @return cleanupPrd  The cleanupPrd of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public Integer getCleanupPrd() {
    return cleanupPrd;
  }

  /**
   * Set the cleanupPrd of this {@link PrintQueueDTO} instance.
   *
   * @param cleanupPrd  The cleanupPrd of this {@link PrintQueueDTO}
   */
  public void setCleanupPrd( @Nonnull final Integer cleanupPrd) {
    this.cleanupPrd = cleanupPrd;
  }

   /**
    * Set the techUserName of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param techUserName  The techUserName of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO techUserName(@Nonnull final String techUserName) {
    this.techUserName = techUserName;
    return this;
  }

   /**
    * Get techUserName
    * @return techUserName  The techUserName of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public String getTechUserName() {
    return techUserName;
  }

  /**
   * Set the techUserName of this {@link PrintQueueDTO} instance.
   *
   * @param techUserName  The techUserName of this {@link PrintQueueDTO}
   */
  public void setTechUserName( @Nonnull final String techUserName) {
    this.techUserName = techUserName;
  }

   /**
    * Set the creator of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param creator  The creator of this {@link PrintQueueDTO}
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO creator(@Nonnull final String creator) {
    this.creator = creator;
    return this;
  }

   /**
    * Get creator
    * @return creator  The creator of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public String getCreator() {
    return creator;
  }

  /**
   * Set the creator of this {@link PrintQueueDTO} instance.
   *
   * @param creator  The creator of this {@link PrintQueueDTO}
   */
  public void setCreator( @Nonnull final String creator) {
    this.creator = creator;
  }

   /**
    * Set the createdOn of this {@link PrintQueueDTO} instance and return the same instance.
    *
    * @param createdOn  Creation date
    * @return The same instance of this {@link PrintQueueDTO} class
    */
   @Nonnull public PrintQueueDTO createdOn(@Nonnull final LocalDate createdOn) {
    this.createdOn = createdOn;
    return this;
  }

   /**
    * Creation date
    * @return createdOn  The createdOn of this {@link PrintQueueDTO} instance.
    */
  @Nonnull public LocalDate getCreatedOn() {
    return createdOn;
  }

  /**
   * Set the createdOn of this {@link PrintQueueDTO} instance.
   *
   * @param createdOn  Creation date
   */
  public void setCreatedOn( @Nonnull final LocalDate createdOn) {
    this.createdOn = createdOn;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PrintQueueDTO}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PrintQueueDTO} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("PrintQueueDTO has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link PrintQueueDTO} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PrintQueueDTO printQueueDTO = (PrintQueueDTO) o;
    return Objects.equals(this.cloudSdkCustomFields, printQueueDTO.cloudSdkCustomFields) &&
        Objects.equals(this.qname, printQueueDTO.qname) &&
        Objects.equals(this.qdescription, printQueueDTO.qdescription) &&
        Objects.equals(this.qstatus, printQueueDTO.qstatus) &&
        Objects.equals(this.qformat, printQueueDTO.qformat) &&
        Objects.equals(this.cleanupPrd, printQueueDTO.cleanupPrd) &&
        Objects.equals(this.techUserName, printQueueDTO.techUserName) &&
        Objects.equals(this.creator, printQueueDTO.creator) &&
        Objects.equals(this.createdOn, printQueueDTO.createdOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(qname, qdescription, qstatus, qformat, cleanupPrd, techUserName, creator, createdOn, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PrintQueueDTO {\n");
    sb.append("    qname: ").append(toIndentedString(qname)).append("\n");
    sb.append("    qdescription: ").append(toIndentedString(qdescription)).append("\n");
    sb.append("    qstatus: ").append(toIndentedString(qstatus)).append("\n");
    sb.append("    qformat: ").append(toIndentedString(qformat)).append("\n");
    sb.append("    cleanupPrd: ").append(toIndentedString(cleanupPrd)).append("\n");
    sb.append("    techUserName: ").append(toIndentedString(techUserName)).append("\n");
    sb.append("    creator: ").append(toIndentedString(creator)).append("\n");
    sb.append("    createdOn: ").append(toIndentedString(createdOn)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

