

/*
 * SAP Print Service
 * SAP Print service offers public APIs, including Query Print Queue, Upload Documents and Create Print Task that can help manage print queues, connect print clients and monitor print status.   This API is implemented based on REST API specification.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.print.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * PrintProfileDTO
 */
// CHECKSTYLE:OFF
public class PrintProfileDTO 
// CHECKSTYLE:ON
{
  @JsonProperty("queueName")
  private String queueName;

  @JsonProperty("profileName")
  private String profileName;

  @JsonProperty("profileParams")
  private String profileParams;

  @JsonProperty("profileStatus")
  private String profileStatus;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the queueName of this {@link PrintProfileDTO} instance and return the same instance.
    *
    * @param queueName  The queueName of this {@link PrintProfileDTO}
    * @return The same instance of this {@link PrintProfileDTO} class
    */
   @Nonnull public PrintProfileDTO queueName(@Nonnull final String queueName) {
    this.queueName = queueName;
    return this;
  }

   /**
    * Get queueName
    * @return queueName  The queueName of this {@link PrintProfileDTO} instance.
    */
  @Nonnull public String getQueueName() {
    return queueName;
  }

  /**
   * Set the queueName of this {@link PrintProfileDTO} instance.
   *
   * @param queueName  The queueName of this {@link PrintProfileDTO}
   */
  public void setQueueName( @Nonnull final String queueName) {
    this.queueName = queueName;
  }

   /**
    * Set the profileName of this {@link PrintProfileDTO} instance and return the same instance.
    *
    * @param profileName  The profileName of this {@link PrintProfileDTO}
    * @return The same instance of this {@link PrintProfileDTO} class
    */
   @Nonnull public PrintProfileDTO profileName(@Nonnull final String profileName) {
    this.profileName = profileName;
    return this;
  }

   /**
    * Get profileName
    * @return profileName  The profileName of this {@link PrintProfileDTO} instance.
    */
  @Nonnull public String getProfileName() {
    return profileName;
  }

  /**
   * Set the profileName of this {@link PrintProfileDTO} instance.
   *
   * @param profileName  The profileName of this {@link PrintProfileDTO}
   */
  public void setProfileName( @Nonnull final String profileName) {
    this.profileName = profileName;
  }

   /**
    * Set the profileParams of this {@link PrintProfileDTO} instance and return the same instance.
    *
    * @param profileParams  The profileParams of this {@link PrintProfileDTO}
    * @return The same instance of this {@link PrintProfileDTO} class
    */
   @Nonnull public PrintProfileDTO profileParams(@Nonnull final String profileParams) {
    this.profileParams = profileParams;
    return this;
  }

   /**
    * Get profileParams
    * @return profileParams  The profileParams of this {@link PrintProfileDTO} instance.
    */
  @Nonnull public String getProfileParams() {
    return profileParams;
  }

  /**
   * Set the profileParams of this {@link PrintProfileDTO} instance.
   *
   * @param profileParams  The profileParams of this {@link PrintProfileDTO}
   */
  public void setProfileParams( @Nonnull final String profileParams) {
    this.profileParams = profileParams;
  }

   /**
    * Set the profileStatus of this {@link PrintProfileDTO} instance and return the same instance.
    *
    * @param profileStatus  The profileStatus of this {@link PrintProfileDTO}
    * @return The same instance of this {@link PrintProfileDTO} class
    */
   @Nonnull public PrintProfileDTO profileStatus(@Nonnull final String profileStatus) {
    this.profileStatus = profileStatus;
    return this;
  }

   /**
    * Get profileStatus
    * @return profileStatus  The profileStatus of this {@link PrintProfileDTO} instance.
    */
  @Nonnull public String getProfileStatus() {
    return profileStatus;
  }

  /**
   * Set the profileStatus of this {@link PrintProfileDTO} instance.
   *
   * @param profileStatus  The profileStatus of this {@link PrintProfileDTO}
   */
  public void setProfileStatus( @Nonnull final String profileStatus) {
    this.profileStatus = profileStatus;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PrintProfileDTO}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PrintProfileDTO} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("PrintProfileDTO has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link PrintProfileDTO} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PrintProfileDTO printProfileDTO = (PrintProfileDTO) o;
    return Objects.equals(this.cloudSdkCustomFields, printProfileDTO.cloudSdkCustomFields) &&
        Objects.equals(this.queueName, printProfileDTO.queueName) &&
        Objects.equals(this.profileName, printProfileDTO.profileName) &&
        Objects.equals(this.profileParams, printProfileDTO.profileParams) &&
        Objects.equals(this.profileStatus, printProfileDTO.profileStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(queueName, profileName, profileParams, profileStatus, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PrintProfileDTO {\n");
    sb.append("    queueName: ").append(toIndentedString(queueName)).append("\n");
    sb.append("    profileName: ").append(toIndentedString(profileName)).append("\n");
    sb.append("    profileParams: ").append(toIndentedString(profileParams)).append("\n");
    sb.append("    profileStatus: ").append(toIndentedString(profileStatus)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

