

/*
 * SAP Print Service
 * SAP Print service offers public APIs, including Query Print Queue, Upload Documents and Create Print Task that can help manage print queues, connect print clients and monitor print status.   This API is implemented based on REST API specification.
 *
 * The version of the OpenAPI document: 1.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package customer.caplabelprinting1.btpservice.print.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import customer.caplabelprinting1.btpservice.print.model.PrintTaskMetadataBusinessMetadata;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonAnyGetter;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * PrintTaskMetadata
 */
// CHECKSTYLE:OFF
public class PrintTaskMetadata 
// CHECKSTYLE:ON
{
  @JsonProperty("business_metadata")
  private PrintTaskMetadataBusinessMetadata businessMetadata;

  @JsonProperty("version")
  private BigDecimal version;

  @JsonAnySetter
  @JsonAnyGetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
    * Set the businessMetadata of this {@link PrintTaskMetadata} instance and return the same instance.
    *
    * @param businessMetadata  The businessMetadata of this {@link PrintTaskMetadata}
    * @return The same instance of this {@link PrintTaskMetadata} class
    */
   @Nonnull public PrintTaskMetadata businessMetadata(@Nonnull final PrintTaskMetadataBusinessMetadata businessMetadata) {
    this.businessMetadata = businessMetadata;
    return this;
  }

   /**
    * Get businessMetadata
    * @return businessMetadata  The businessMetadata of this {@link PrintTaskMetadata} instance.
    */
  @Nonnull public PrintTaskMetadataBusinessMetadata getBusinessMetadata() {
    return businessMetadata;
  }

  /**
   * Set the businessMetadata of this {@link PrintTaskMetadata} instance.
   *
   * @param businessMetadata  The businessMetadata of this {@link PrintTaskMetadata}
   */
  public void setBusinessMetadata( @Nonnull final PrintTaskMetadataBusinessMetadata businessMetadata) {
    this.businessMetadata = businessMetadata;
  }

   /**
    * Set the version of this {@link PrintTaskMetadata} instance and return the same instance.
    *
    * @param version  The version of this {@link PrintTaskMetadata}
    * @return The same instance of this {@link PrintTaskMetadata} class
    */
   @Nonnull public PrintTaskMetadata version(@Nonnull final BigDecimal version) {
    this.version = version;
    return this;
  }

   /**
    * Get version
    * @return version  The version of this {@link PrintTaskMetadata} instance.
    */
  @Nonnull public BigDecimal getVersion() {
    return version;
  }

  /**
   * Set the version of this {@link PrintTaskMetadata} instance.
   *
   * @param version  The version of this {@link PrintTaskMetadata}
   */
  public void setVersion( @Nonnull final BigDecimal version) {
    this.version = version;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link PrintTaskMetadata}.
   * @return The set of properties names
   */
  @JsonIgnore
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of this {@link PrintTaskMetadata} instance.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("PrintTaskMetadata has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  /**
   * Set an unrecognizable property of this {@link PrintTaskMetadata} instance. If the map previously contained a mapping
   * for the key, the old value is replaced by the specified value.
   * @param customFieldName The name of the property
   * @param customFieldValue The value of the property
   */
  @JsonIgnore
  public void setCustomField( @Nonnull String customFieldName, @Nullable Object customFieldValue )
  {
      cloudSdkCustomFields.put(customFieldName, customFieldValue);
  }


  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final PrintTaskMetadata printTaskMetadata = (PrintTaskMetadata) o;
    return Objects.equals(this.cloudSdkCustomFields, printTaskMetadata.cloudSdkCustomFields) &&
        Objects.equals(this.businessMetadata, printTaskMetadata.businessMetadata) &&
        Objects.equals(this.version, printTaskMetadata.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(businessMetadata, version, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class PrintTaskMetadata {\n");
    sb.append("    businessMetadata: ").append(toIndentedString(businessMetadata)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


}

